apiVersion: apps/v1
kind: Deployment
metadata:
  name: projecthelloworld
  labels:
    app: helloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: nananoam123/final-project:0.0.1
        ports:
        - containerPort: 8080