apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    run: helloworld
spec:
  selector:
    app.kubernetes.io/name: projecthelloworld
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080